import React from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, Clock, Calendar, Activity, AlignLeft, Info } from 'lucide-react';
import { translations } from '../utils/translations';

const TimelineDetailModal = ({ isOpen, onClose, event, language }) => {
  const t = translations[language || 'English'] || translations.English;
  if (!isOpen || !event) return null;

  return (
    <AnimatePresence>
      <div className="fixed inset-0 z-[70] flex items-center justify-center p-4 bg-black/40 backdrop-blur-sm">
        <motion.div
          initial={{ opacity: 0, scale: 0.9, y: 20 }}
          animate={{ opacity: 1, scale: 1, y: 0 }}
          exit={{ opacity: 0, scale: 0.9, y: 20 }}
          className="bg-white dark:bg-[#0b1437] w-full max-w-md rounded-[2.5rem] shadow-2xl border border-slate-100 dark:border-slate-800 overflow-hidden"
        >
          <div className="relative p-8">
            <button 
              onClick={onClose} 
              className="absolute top-6 right-6 p-2 hover:bg-slate-100 dark:hover:bg-slate-800 rounded-xl transition-colors"
            >
              <X className="w-5 h-5 text-slate-400" />
            </button>

            <div className="flex items-center gap-4 mb-8">
              <div className="p-4 bg-indigo-500/10 text-indigo-500 rounded-2xl shadow-inner">
                <Activity className="w-7 h-7" />
              </div>
              <div>
                <h2 className="text-2xl font-black text-slate-900 dark:text-white leading-tight">{event.title}</h2>
                <span className="text-[10px] font-black text-indigo-500 uppercase tracking-[0.2em]">{event.type || 'AI Analysis'}</span>
              </div>
            </div>

            <div className="space-y-6">
              <div className="grid grid-cols-2 gap-4">
                <div className="p-4 rounded-2xl bg-slate-50 dark:bg-slate-800/40 border border-slate-100 dark:border-slate-700/50">
                  <div className="flex items-center gap-2 mb-2 text-slate-400">
                    <Calendar className="w-3.5 h-3.5" />
                    <span className="text-[10px] font-black uppercase tracking-widest">{t.date}</span>
                  </div>
                  <p className="text-sm font-bold text-slate-700 dark:text-slate-200">{event.date}</p>
                </div>
                <div className="p-4 rounded-2xl bg-slate-50 dark:bg-slate-800/40 border border-slate-100 dark:border-slate-700/50">
                  <div className="flex items-center gap-2 mb-2 text-slate-400">
                    <Clock className="w-3.5 h-3.5" />
                    <span className="text-[10px] font-black uppercase tracking-widest">{t.time || 'Time'}</span>
                  </div>
                  <p className="text-sm font-bold text-slate-700 dark:text-slate-200">{event.time}</p>
                </div>
              </div>

              <div className="p-6 rounded-3xl bg-indigo-50/50 dark:bg-indigo-500/5 border border-indigo-100 dark:border-indigo-500/10">
                <div className="flex items-center gap-2 mb-4 text-indigo-500">
                  <AlignLeft className="w-4 h-4" />
                  <span className="text-[10px] font-black uppercase tracking-widest">{t.clinicalNotes}</span>
                </div>
                <div className="prose prose-sm dark:prose-invert max-w-none">
                  <p className="text-sm leading-relaxed text-slate-600 dark:text-slate-300 italic">
                    "{event.description || 'No additional notes provided for this record.'}"
                  </p>
                </div>
              </div>

              <div className="flex items-center gap-3 p-4 rounded-2xl bg-amber-50 dark:bg-amber-500/5 border border-amber-100 dark:border-amber-500/10">
                <Info className="w-5 h-5 text-amber-500 flex-shrink-0" />
                <p className="text-[11px] font-medium text-amber-700 dark:text-amber-400 leading-tight">
                  This record is generated by MediScan AI and is part of your permanent clinical history.
                </p>
              </div>

              <button
                onClick={onClose}
                className="w-full py-4 mt-2 bg-slate-900 dark:bg-white text-white dark:text-slate-900 font-black rounded-2xl shadow-xl transition-all hover:scale-[1.02] active:scale-[0.98]"
              >
                {t.clear || 'Close Details'}
              </button>
            </div>
          </div>
        </motion.div>
      </div>
    </AnimatePresence>
  );
};

export default TimelineDetailModal;
