import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, ShieldCheck, Zap, Brain } from 'lucide-react';
import { motion } from 'framer-motion';
import { translations } from '../utils/translations';

function Home({ themeContext }) {
  const [isDarkMode, setIsDarkMode, language, setLanguage] = themeContext;
  const t = translations[language] || translations.English;
  const user = localStorage.getItem('user');

  const features = [
    {
      icon: <Brain className="w-6 h-6 text-indigo-600" />,
      title: 'AI-Powered Diagnostics',
      description: 'Leveraging advanced Random Forest models trained on diverse medical datasets for accurate disease prediction.',
    },
    {
      icon: <Zap className="w-6 h-6 text-amber-500" />,
      title: 'Instant Explanations',
      description: 'Get immediate, doctor-like explanations and actionable medical advice generated by Gemini AI.',
    },
    {
      icon: <ShieldCheck className="w-6 h-6 text-emerald-500" />,
      title: 'Reliable & Secure',
      description: 'Your symptom inputs are processed securely to provide personalized lifestyle and treatment recommendations.',
    },
  ];

  return (
    <div className={`min-h-screen font-sans selection:bg-indigo-100 selection:text-indigo-900 transition-colors duration-500 ${isDarkMode ? 'bg-[#0b1437]' : 'bg-slate-50'}`}>
      {/* Navigation */}
      <nav className={`fixed top-0 left-0 right-0 h-20 backdrop-blur-xl border-b z-50 px-6 flex items-center justify-between transition-all ${isDarkMode ? 'bg-[#0b1437]/80 border-white/5 shadow-2xl shadow-black/20' : 'bg-white/80 border-slate-200'}`}>
        <div className="flex items-center gap-2">
          <div className="w-10 h-10 rounded-2xl bg-indigo-600 flex items-center justify-center shadow-lg shadow-indigo-500/20">
            <Brain className="w-6 h-6 text-white" />
          </div>
          <span className={`font-black text-xl tracking-tight ${isDarkMode ? 'text-white' : 'text-slate-900'}`}>MEDISCAN AI</span>
        </div>
        <div className="flex items-center gap-4 sm:gap-8">
          <div className="hidden sm:flex items-center gap-6">
            <Link to="/about" className={`text-sm font-bold transition-colors ${isDarkMode ? 'text-slate-400 hover:text-white' : 'text-slate-600 hover:text-indigo-600'}`}>{t.about}</Link>
            <Link to="/contact" className={`text-sm font-bold transition-colors ${isDarkMode ? 'text-slate-400 hover:text-white' : 'text-slate-600 hover:text-indigo-600'}`}>{t.contact}</Link>
          </div>
          {user ? (
            <Link to="/dashboard" className="px-6 py-2.5 bg-indigo-600 text-white rounded-xl text-sm font-black hover:bg-indigo-700 transition-all shadow-xl shadow-indigo-500/20">{t.dashboard}</Link>
          ) : (
            <Link to="/login" className={`px-6 py-2.5 rounded-xl text-sm font-black transition-all ${isDarkMode ? 'bg-white text-slate-900 hover:bg-slate-100 shadow-xl shadow-white/5' : 'bg-slate-900 text-white hover:bg-slate-800'}`}>{t.login}</Link>
          )}
        </div>
      </nav>

      {/* Hero Section */}
      <section className="pt-40 pb-32 px-6 relative overflow-hidden">
        {/* Animated Background Blobs */}
        {isDarkMode && (
          <>
            <div className="absolute top-1/4 left-1/4 w-64 h-64 bg-indigo-600/20 rounded-full blur-[100px] animate-pulse"></div>
            <div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-blue-600/10 rounded-full blur-[120px] animate-pulse" style={{ animationDelay: '2s' }}></div>
          </>
        )}
        
        <div className="max-w-6xl mx-auto text-center relative z-10">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, ease: "easeOut" }}
          >
            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-indigo-500/10 text-indigo-500 text-xs font-black uppercase tracking-widest mb-8 border border-indigo-500/20">
              <Sparkles className="w-4 h-4" />
              {t.aiAnalysisComplete || 'Advanced Diagnostic AI'}
            </div>
            <h1 className={`text-5xl md:text-8xl font-black leading-tight mb-8 tracking-tighter ${isDarkMode ? 'text-white' : 'text-slate-900'}`}>
              {t.heroTitle} <br/>
              <span className="text-transparent bg-clip-text bg-gradient-to-r from-indigo-500 via-purple-500 to-blue-500">
                {t.heroTitleHighlight}
              </span>
            </h1>
            <p className={`text-lg md:text-2xl max-w-3xl mx-auto mb-12 leading-relaxed font-medium ${isDarkMode ? 'text-slate-400' : 'text-slate-600'}`}>
              {t.heroSubtitle}
            </p>
            <div className="flex flex-col sm:flex-row items-center justify-center gap-6">
              <Link 
                to={user ? "/dashboard" : "/signup"} 
                className="w-full sm:w-auto px-10 py-5 bg-indigo-600 text-white rounded-[2rem] font-black text-lg flex items-center justify-center gap-3 hover:bg-indigo-700 transition-all shadow-2xl shadow-indigo-500/40 hover:scale-105 active:scale-95"
              >
                {user ? t.dashboard : t.getStarted}
                <ArrowRight className="w-6 h-6" />
              </Link>
              <Link 
                to="/about" 
                className={`w-full sm:w-auto px-10 py-5 border-2 rounded-[2rem] font-black text-lg transition-all hover:scale-105 active:scale-95 ${
                  isDarkMode 
                  ? 'bg-white/5 border-white/10 text-white hover:bg-white/10' 
                  : 'bg-white border-slate-200 text-slate-700 hover:bg-slate-50 shadow-lg shadow-slate-200/50'
                }`}
              >
                {t.learnMore}
              </Link>
            </div>
          </motion.div>
        </div>
      </section>

      {/* Features */}
      <section className="py-32 px-6 relative z-10">
        <div className="max-w-6xl mx-auto grid grid-cols-1 md:grid-cols-3 gap-8">
          {features.map((feature, idx) => (
            <motion.div 
              key={idx}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: idx * 0.2 }}
              className={`p-10 rounded-[2.5rem] border transition-all group ${
                isDarkMode 
                ? 'glass-dark border-white/5 hover:border-indigo-500/50' 
                : 'bg-white border-slate-100 shadow-xl shadow-slate-200/20 hover:border-indigo-100'
              }`}
            >
              <div className={`w-16 h-16 rounded-2xl flex items-center justify-center mb-8 transition-all group-hover:scale-110 group-hover:rotate-6 ${
                isDarkMode ? 'bg-indigo-500/20 text-indigo-400' : 'bg-indigo-50 text-indigo-600'
              }`}>
                {feature.icon}
              </div>
              <h3 className={`text-2xl font-black mb-4 ${isDarkMode ? 'text-white' : 'text-slate-900'}`}>{feature.title}</h3>
              <p className={`text-base leading-relaxed font-medium ${isDarkMode ? 'text-slate-400' : 'text-slate-600'}`}>{feature.description}</p>
            </motion.div>
          ))}
        </div>
      </section>

      {/* Scroll to Top Button */}
      <button
        id="home-scroll-top"
        onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}
        className="fixed bottom-8 right-8 p-5 bg-indigo-600 text-white rounded-3xl shadow-2xl shadow-indigo-500/40 transition-all duration-500 opacity-0 pointer-events-none translate-y-10 hover:scale-110 active:scale-90 z-50 group overflow-hidden"
      >
        <div className="absolute inset-0 bg-gradient-to-tr from-white/20 to-transparent opacity-0 group-hover:opacity-100 transition-opacity"></div>
        <ArrowRight className="w-6 h-6 relative z-10 -rotate-90" />
      </button>

      <script>
        {React.useEffect(() => {
          const handleScroll = () => {
            const btn = document.getElementById('home-scroll-top');
            if (btn) {
              if (window.scrollY > 400) {
                btn.style.opacity = '1';
                btn.style.pointerEvents = 'auto';
                btn.style.transform = 'translateY(0)';
              } else {
                btn.style.opacity = '0';
                btn.style.pointerEvents = 'none';
                btn.style.transform = 'translateY(40px)';
              }
            }
          };
          window.addEventListener('scroll', handleScroll);
          return () => window.removeEventListener('scroll', handleScroll);
        }, [])}
      </script>
    </div>
  );
}

export default Home;
